server:
  port: 8081

spring:
  application:
    name: Security
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:wookie_books
    username: wookie
    password: wookie_books
jwt:
    secret: 293D66AE74131FEAABCC5CC02DD82E1ABE48C1FAE5D8ACDF51AA073E281441F4
    token:
        expiration_time: 600000
    refresh_token:
        expiration_time: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
